let allowedAgents = [
  { name: "My OTT PLAYER", ua: "OTT Player/1.7.4.1 (Linux;Android 13; en; ewzbl4)" },
  { name: "My OTT NAVIGATOR", ua: "OTT Navigator/1.7.3.1 (Linux;Android 13; en; zdokxl)" },
  { name: "My OTT TV", ua: "OTT TV/1.7.2.2 (Linux;Android 13; en; 1mfhuaz)" },
  { name: "Denis yap jan24 ✅", ua: "OTT TV/1.7.4.1 (Linux;Android 11; en; prkmm2)" },
  { name: "Denis yap2 jan24 ✅", ua: "OTT TV/1.7.4.1 (Linux;Android 11; en; 1fx95ew)" }
];
